### ISSUE TITLE
Swap logic of 'SCRIPT_STYLE_PUSH_ENABLED' env var

### ISSUE THREAD

**Issue by julian-mair** [codemonkey1988/script-style-push#10]
At the moment you have to set the **SCRIPT_STYLE_PUSH_ENABLED**  env variable to **disable** the extension. (So it's written in the README)

This sounds false.

But in general, wouldn't it be a better solution, if we swap the behaviour so that only we have to set the env var **SCRIPT_STYLE_PUSH_DISABLED** if we want to disable it? 
IF not set, everything should work out-of-the-box from the begin on.

see pull request: #9

**Comment by codemonkey1988** [comment]
Hi, thank you for this notice and the corresponding PR.
You are absolutely right with this. I will merge it and release it with the next release with a contribution note :)

**Comment by julian-mair** [comment]
awesome! :) thank you very much!
